# Generated by Django 4.0.4 on 2022-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_alter_listings_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biddings',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
