# Generated by Django 4.0.4 on 2022-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='init_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
