# Generated by Django 4.0.4 on 2022-06-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_highest_bid_listing_curren_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='curren_price',
            new_name='current_price',
        ),
    ]
