# Generated by Django 4.0.4 on 2022-06-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
            ],
        ),
    ]
