# Generated by Django 4.0.4 on 2022-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Listing',
            new_name='listing',
        ),
    ]
